version: '3.3'
services:
  rest-api-service:
    build:
      context: .
      dockerfile: rest-api-service/docker/Dockerfile
    network_mode: host
  newsapi-service:
    build:
      context: .
      dockerfile: newsapi-service/docker/Dockerfile
    network_mode: host
  elk:
    image: sebp/elk
    environment:
      ELASTICSEARCH_START: 1
      KIBANA_START: 0
      LOGSTASH_START: 0
    network_mode: host

