version: '3.3'
services:
  rest-api-service:
    build:
      context: .
      dockerfile: rest-api-service/docker/Dockerfile
    ports:
      - "8080:8080"
  newsapi-service:
    build:
      context: .
      dockerfile: newsapi-service/docker/Dockerfile
    ports:
     - "8081:8080"
  elk:
    image: sebp/elk
    environment:
      ELASTICSEARCH_START: 1
      KIBANA_START: 0
      LOGSTASH_START: 0
    ports:
    - "5601:5601"
    - "9200:9200"
    - "9300:9300"
